export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const LIBR_ROUTE = '/'
export const BOOKMARK_ROUTE = '/bookmark'
export const BOOK_ROUTE = '/book'